export interface Numero {
    seqNumeros: number;
    codProduto: number | null;
    data: string | null;
    quedaAssociado: number | null;
    quedaPremio: number | null;
    vendasTlmkt: number;
    vendasReativacao: number;
    vendasCentral: number | null;
    vendasTotais: number | null;
    vendasOutrosProjetos: number | null;
    ticketMedio: number | null;
    vigentes: number | null;
    proposta: number | null;
    negados: number | null;
    acordos: number | null;
    numeroAntigo: number | null;
    quantidadeVendas: number | null;
    indiceQuedaNovo: string;
    indiceQuedaAntigo: string;
    projecaoDeVendas: number | null;
    porcPagAcordo: number | null;
    pagPrimParcela: number | null;
    indiceOutrasParcela: number | null;
    mediaPermanecia: number | null;
    indiceCrescimento: number | null;
    n1: number | null;
    n2: number | null;
    pn: number | null;
    ativosNegados: number | null;
    a: number | null;
    pa: number | null;
    cancVig: number | null;
    pnSAcordo: number | null;
    n1SAcordo: number | null;
    n2SAcordo: number | null;
    cancCentral: number | null;
    reversao: number | null;
    entradaInadimplencia: number | null;
    upSelling: number | null;
    perda: number | null;
    vencidos: number | null;
}